### ISSUE TITLE
Better Optionals

### ISSUE THREAD

**Issue by OliverBrotchie** [OliverBrotchie/optionals#1]
As noted in [this](https://www.reddit.com/r/rust/comments/puo50z/comment/he7jl2g/?utm_source=share&utm_medium=web2x&context=3) comment, Result and Option may need an improvement. 

I have come up with three different implementations based on the comments which you can find [here](https://gist.github.com/OliverBrotchie/319ae829eb901f33072ee9e3cc933153). 
My personal favourite is option one, as it uses native types and symbols instead of classes, however, it does make pattern matching harder.

What do you think about this?

**Comment by wongjiahau** [comment]
Why isn't discriminated union one of the alternative solution?

**Comment by OliverBrotchie** [comment]
Apologies I didn't add it as turned out to be nearly identical to [how fp-ts handles options](https://github.com/gcanti/fp-ts/blob/master/src/Option.ts)!

**Comment by Aloso** [comment]
@OliverBrotchie my opinion is that OptionOne (the current implementation) is the least useful one, because it doesn't have combinators such as `map`, `orElse`, `andThen`, etc. Typescript doesn't have Rust's `?` operator, nor convenient pattern matching, so combinators would be the most convenient way to use `Option` or `Result`.

**Comment by OliverBrotchie** [comment]
> @OliverBrotchie my opinion is that OptionOne (the current implementation) is the least useful one, because it doesn't have combinators such as `map`, `orElse`, `andThen`, etc. Typescript doesn't have Rust's `?` operator, nor convenient pattern matching, so combinators would be the most convenient way to use `Option` or `Result`.

None of these examples is fully implemented yet and don't include the map, unwrapOr, unwrapElse etc that would be in the final version. Option one is also not the same as the current implementation and I intend to write exhaustive + non-exhaustive match functions to better handle these types!

**Comment by OliverBrotchie** [comment]
See [Gist](https://gist.github.com/OliverBrotchie/9a718512120dac47a1e330e04455d5f7) for match example. The essential trade-off here is ease-of-use and perfect performance vs strong type security.
