### ISSUE TITLE
NPM Availability

### ISSUE THREAD

**Issue by jeff-v** [OliverBrotchie/optionals#3]
This library looks fantastic! However, I can't readily use it on projects at work in its current state since we're mostly working with React and Node, so would you mind adding it to NPM, or would you prefer that I fork it and push it myself?

Thanks for all your work on this!

**Comment by OliverBrotchie** [comment]
@jeff-v Thank you, that really means a lot! 

I didn't realize that Node doesn't support propper ES6 imports. If you would like to open a PR I would happily merge and publish the necessary changes! My only worry is that it may be hard to structure the repository in a way that is easily consumable from one index, due to the two different type systems.

**Comment by OliverBrotchie** [comment]
@jeff-v I can make the changes myself if you would rather.

**Comment by jeff-v** [comment]
Sorry, things have been crazy over the past month, it would be awesome if you wanted to make the changes but I understand if time can be an issue (like it was for me)

**Comment by ianchanning** [comment]
> @jeff-v Thank you, that really means a lot!
> 
> I didn't realize that Node doesn't support propper ES6 imports. If you would like to open a PR I would happily merge and publish the necessary changes! My only worry is that it may be hard to structure the repository in a way that is easily consumable from one index, due to the two different type systems.

Perhaps it might be better to split this project in two? One for hard types and one for soft types

**Comment by aaronhuggins** [comment]
Hey @jeff-v and @OliverBrotchie I'll open a PR for this as I've done an NPM workflow in many of my Deno repos for portability.

Examples (`nice_threads` is overly complex due to some unique deps, your repo here is super simple):

https://github.com/aaronhuggins/cbor-redux
https://github.com/aaronhuggins/nice_threads

**Comment by aaronhuggins-carewell** [comment]
I've been working on a port of these optionals myself, but this is solid and I think I'd rather use this.

**Comment by andrew-pyle** [comment]
This project looks very interesting! I was linked here from [TC39 Proposal for ECMAScript Pattern Matching](https://github.com/tc39/proposal-pattern-matching).

Is this up on NPM? I'm interested in using this project in browser code. If it is up on NPM, could we get that link in the README?

**Comment by ianchanning** [comment]
> This project looks very interesting! I was linked here from [TC39 Proposal for ECMAScript Pattern Matching](https://github.com/tc39/proposal-pattern-matching).
> 
> Is this up on NPM? I'm interested in using this project in browser code. If it is up on NPM, could we get that link in the README?

It doesn't look like it is up on NPM yet. If you look in [build_npm.json](https://github.com/OliverBrotchie/optionals/pull/5/files#diff-917baa774332d4820420ccdb24d07179c0c78af1a1ec9403bb944e5ce4f2788e) the npm package name should be `rust-optionals`. However I think it still requires @OliverBrotchie to run `npm publish`.

**Comment by OliverBrotchie** [comment]
Hey @ianchanning @andrew-pyle thank you so much for your interest! I was hoping to implement #6 before I published a version to NPM as it may introduce breaking changes to `from`. I will be working on this feature later tonight and will keep this thread up to date.

**Comment by OliverBrotchie** [comment]
#6 [Convenience helpers and improved spec compliance] has now been merged - I will draft a new release and publish to NPM later tonight!

**Comment by aaronhuggins** [comment]
@OliverBrotchie Excited! Looking to introduce this into my employer's codebase over the next month or two.

Definitely going to switch my private deno projects from their current implementation.

**Comment by OliverBrotchie** [comment]
@aaronhuggins Aww that's amazing!!! 🥳

Thank you so so much for your help! ❤️

**Comment by OliverBrotchie** [comment]
**Optionals** `v3.0.0` has now been released on NPM, thank you all for waiting for so long! 🎉🎉

*Example usage:*
```sh
npm install rust-optionals
```

**Comment by ianchanning** [comment]
Yay! Wonderful, thanks @OliverBrotchie ❤️
