### ISSUE TITLE
Feature requests: convenience helpers and improved spec compliance

### ISSUE THREAD

**Issue by aaronhuggins** [OliverBrotchie/optionals#6]
Some features that I'd like to contribute from my personal implementation that this one is missing. Opening issue for discussion before just opening a pull request to help eliminate unnecessary work. Some of these are convenience, some of these bring the implementations closer to the Rust spec. Porting these is little effort, as the code already exists in my own personal work.

*Convenience helpers*
- [x] `function fromPromise<V, E extends Error>(promise: Promise<V>): Promise<Result<V, E>>`; avoids additional microtasks
- [x] `function fromSync<V, E extends Error>(func: () => V): Result<V, E>`; synchronous helper, avoids microtasks completely
- [x] `Symbol.toStringTag` support; useful to quickly and easily distinguish resulting objects
- [x] `Symbol.hasInstance` support on `Err`, `Ok`, `Some`, `None`; example `myResult instance of Err`

*Spec compliance*
- [x] Iterable support, similar to `class Result<T, E extends Error> implements Iterable<T>`
- [x] `Result.expectErr`

**Comment by OliverBrotchie** [comment]
Hey man, thanks for opening an issue I really appreciate the interest!  Here are my thoughts:

*Convenience helpers*
- I definitely agree about separating out synchronous and asynchronous `from`s. I think the best naming convention for this would be to have `from` as the sync method and `fromPromise` as the async method.
- `Symbol.toStringTag`, could you give an example of how this might be used?
- `Symbol.hasInstance`, 100% that's a good shout.

*Spec Compliance*
- Iterable support, what would an implementation of this look like? 
- `Result.expectErr`, again this is definitely a good inclusion.

**Comment by aaronhuggins** [comment]
Thanks for getting back to me! I appreciate the positive response and feedback, that's cool.

_Convenience helpers_

* Hard agree on this point; one reason I had for suggesting an alternate naming conventions is that an async `from` already exists and I was concerned with breaking changes. If braking changes are okay, I think this is a welcome adjustment to the API.
* `Symbol.toStringTag` is used by JS engines when calling `Object.toString` calls; would produce `[object Err]` for example instead of `[object Object]`, which is useful during debugging and with runtime checks some folks use.
* `Symbol.hasInstance` cool.

_Spec Compliance_

* Iterable support allows easy access to the value if any; a `for...of` would have either a single iteration or no iteration, and `Array.from` could be used. It's a type of transposition pattern in Rust which I find useful. Could be either an implicit `implements Iterable<T>` which would be JS "native" or an `iter` method [like Rust](https://doc.rust-lang.org/std/result/enum.Result.html#method.iter)
* `Result.expectErr`, nice.

**Comment by OliverBrotchie** [comment]
@aaronhuggins I have opened a PR with all of the above changes except `Symbol.hasInstance`. 

What did you have in mind for this? Converting `Ok`, `Err` and `Some` to symbols?

**Comment by aaronhuggins** [comment]
Oh! I was literally planning on opening the PR and contributing my existing code. :laughing: 

I'll get you my code samples or get you another PR if you want.

**Comment by OliverBrotchie** [comment]
Oh sorry! 😆

Yeah if you could provide some snippets that would be great!

**Comment by aaronhuggins** [comment]
I'll add as comments in PR.
